### ISSUE TITLE
Highlight overrides not working

### ISSUE THREAD

**Issue by ckt114** [NvChad/base46#195] opened 2023-05-16 13:49 UTC
**Describe the bug**
Highlights overrides are not working.

**To Reproduce**
1. Edit `custom/highlights.lua`
2. Add `fg = "#00cc00"` and `ctermfg = "#00cc00"` to the `Comment` section
3. Restart neovim
4. Run `:hi` and search for `Comment`

**Expected behavior**
The foreground color should be bright green.

**Screenshots**
`custom/highlights.lua`
![image](https://github.com/NvChad/NvChad/assets/573808/36716d91-2248-4df1-acae-c60b2199232f)

`Comment` didn't change.
![image](https://github.com/NvChad/NvChad/assets/573808/6b98d1f1-d0bd-4ac3-a0f4-7605abd32a8c)

**Desktop (please complete the following information):**
 - MacOS Ventura 13.3
 - Kitty or wezterm
 - Version of v0.9.0

**Comment by ckt114** [comment] 2023-05-16 14:04
FYI I tried without `ctermfg` as well but still the same result.

**Comment by siduck** [comment] 2023-05-16 14:36
https://github.com/NvChad/NvChad/assets/59060246/7f9cc0c1-16c2-455d-9f3b-10af476e3fbb

unable to reproduce and also cterm stuff isnt supported by base46

**Comment by ckt114** [comment] 2023-05-16 17:59
It is not helpful to just close the ticket and said that it's not reproducible. I wouldn't have put in a ticket if it's working as expected. I did exactly what you did and it isn't working that's why I put in this ticket for help. What do you suggest me doing to troubleshoot instead?

**Comment by ckt114** [comment] 2023-05-16 18:57
Also, I'm getting error below now and even though I've removed `fg = "#00ccff"` from the highlights.lua the error doesn't stop.

```
Error detected while processing /Users/ckt114/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/ckt114/.local/share/nvim/nvchad/base46/defaults:0: Invalid highlight color: '#00ccff','
stack traceback:
        [C]: in function 'nvim_set_hl'
        /Users/ckt114/.local/share/nvim/nvchad/base46/defaults: in function </Users/ckt114/.local/share/nvim/nvchad/base46/defaults:0>
        [C]: in function 'dofile'
        /Users/ckt114/.config/nvim/init.lua:19: in main chunk
Press ENTER or type command to continue
```

**Comment by siduck** [comment] 2023-05-16 23:49
> Also, I'm getting error below now and even though I've removed `fg = "#00ccff"` from the highlights.lua the error doesn't stop.
> 
> ```
> Error detected while processing /Users/ckt114/.config/nvim/init.lua:
> E5113: Error while calling lua chunk: /Users/ckt114/.local/share/nvim/nvchad/base46/defaults:0: Invalid highlight color: '#00ccff','
> stack traceback:
>         [C]: in function 'nvim_set_hl'
>         /Users/ckt114/.local/share/nvim/nvchad/base46/defaults: in function </Users/ckt114/.local/share/nvim/nvchad/base46/defaults:0>
>         [C]: in function 'dofile'
>         /Users/ckt114/.config/nvim/init.lua:19: in main chunk
> Press ENTER or type command to continue
> ```

please save the file

**Comment by siduck** [comment] 2023-05-16 23:56
Also its not a nvchad issue at all 

![image](https://github.com/NvChad/base46/assets/59060246/49ddab6a-8c9f-4854-8993-c59280000d2b)


cterm fg expects a number and not a string, there's a reason we use guicolors , because they accept hex values

**Comment by siduck** [comment] 2023-05-16 23:57
![image](https://github.com/NvChad/base46/assets/59060246/828e1193-a42d-4860-8af5-551199c59f6b)

i get the same error because you set an invalid value to ctermfg, just remvoe it please

**Comment by ckt114** [comment] 2023-05-16 23:59
I removed both cterm and fg but the error still persist.

**Comment by siduck** [comment] 2023-05-17 00:07
> I removed both cterm and fg but the error still persist.

please save the file!!! 

and do it with neovim, or else your cache would never reload

**Comment by ckt114** [comment] 2023-05-17 00:35
Are you seriously telling me to save the file? That is so condescending man. Forget it dude.

**Comment by siduck** [comment] 2023-05-17 00:39
> Are you seriously telling me to save the file? That is so condescending man. Forget it dude.

Why are you being so rude? Think before you talk 

Our autocmd reloads the theme i.e  recompiles the base46 cache only when you save a file in the custom dir 

![image](https://github.com/NvChad/base46/assets/59060246/a48d8f28-5709-48bb-bafe-ff7b6efc0c2b)


And obviously the autocmd will trigger when you're using neovim only. 

If you're using another editor to save your changes, the cache will never recompile

**Comment by ckt114** [comment] 2023-05-17 00:42
I’m not being rude. You’re being condescending in every issue I reported. Forget that I’ve reported this.

**Comment by siduck** [comment] 2023-05-17 00:45
I'm not, most of the issues we get aren't even related to nvchad or not actual bugs. Its annoying to see them again and again

**Comment by siduck** [comment] 2023-05-17 00:45
https://github.com/NvChad/base46/assets/59060246/c9354593-dc93-4296-97b3-a139d0dd6051

Basically your issue

**Comment by siduck** [comment] 2023-05-17 00:46
I will not close this issue until I hear from you that you dont get the issue anymore

**Comment by ckt114** [comment] 2023-05-17 01:42
I did this again to show you that the error still persist even after I have removed the bad line.

These are the steps I took. I edit everything in nvim.

1. Edit `custom/highlights.lua` and add the bad line `ctermfg = "#00cc00"` into `Comment`
2. Saved the file and quit nvim
3. Started nvim again and the error shown
4. I edited the `custom/highlights.lua` file again and remove that bad `ctermfg` line
5. Saved the file and tried to enter nvim again but the error would not go away

As last resort I had to delete my `~/.local/share/nvim` folder for that error to not show again.

https://github.com/NvChad/base46/assets/573808/fbca5cce-f0a7-48ea-b31a-575b801a2e8b

**Comment by siduck** [comment] 2023-05-17 01:46
weird, can you add ctermfg again, save the file and remove it again and save the file? and make a video out of it

**Comment by ckt114** [comment] 2023-05-17 13:59
@siduck I've recorded from beginning to end on how I produced that unrecoverable error in video below. The only way to stop that error is for me to remove `~/.local/share/nvim` folder.

https://github.com/NvChad/base46/assets/573808/b7e3227d-4920-4024-b38d-69123de02125

**Comment by siduck** [comment] 2023-05-17 14:11
ohh @ckt114 i get the error now! i wasnt facing this issue because i had my neovim window opened. But if there's a corrupted base46 cache, then nvchad wont run at all, it not running properly would mean that the autocmd that compiles and reloads the base46 cache wont get triggered. 

so a quick fix to this rather than deleting whole local nvim config dir is commenting this line in main init.lua

![image](https://github.com/NvChad/base46/assets/59060246/753af802-3380-40f8-a05a-bafc532592e7)

and then save your file again, then uncomment it back :D

**Closed as completed by siduck** 2023-05-17 14:11 UTC

**Comment by ckt114** [comment] 2023-05-17 15:14
I did do that. I commented out that line in init.lua and I didn't get that error but once I fixed the highlights.lua and re-enable that line in init.lua I get the same error again.
