### ISSUE TITLE
REQUEST: Catppuccin Latte, Frappe, and Machiatto

### ISSUE THREAD

**Issue by Vortigern-The-Grey** [NvChad/base46#329] opened 2024-08-13 00:12 UTC
Currently, the catppuccin theme present is Mocha, the darkest and first catppuccin variant. It would be nice to have the other variants as well  :-D

**Comment by siduck** [comment] 2024-08-13 00:14
duplicate of https://github.com/NvChad/base46/issues/327

**Closed as completed by siduck** 2024-08-13 00:14 UTC
